### ISSUE TITLE
React Navigation 5 implementation

### ISSUE THREAD

**Issue by orioletech** [alimek/react-navigation-custom-bottom-tab-component#13]
I'm trying to get this to work with React navigation 5 however I'm really struggling to work out how to do it as all documentation is for previous versions. I've tried to use React Navigation 5's documentation on custom tab bars as well but with no luck. Any help would be fantastic!

**Comment by alimek** [comment]
this was created for v4 and to support v5 it must but totally reworked, so v5 is not supported at the moment, sorry! :(

**Comment by alimek** [comment]
ofc PR is welcome if you wanna make this for v5, this lib was created for "learning" purpose, i am not using this in any of my project, so you will have to fork it any maybe customise for your own.

**Comment by orioletech** [comment]
ah no worries, thanks for the fast reply :)

**Comment by faisal3413** [comment]
well, i also tried to use in r-navigation v5. but became sad to know it is not available for v5. It is really a beautiful component.
